import {
  ChefHat,
  Salad,
  Flame,
  Cake,
  Star,
  Heart,
} from "lucide-react";

export const achievements = [
  {
    id: 1,
    icon: ChefHat,
    title: "Master Chef",
    description: "Cook 100 recipes",
    unlocked: true,
    color: "bg-green-100",
    iconColor: "text-green-700",
  },
  {
    id: 2,
    icon: Salad,
    title: "Healthy Hero",
    description: "Cook 30 healthy meals",
    unlocked: false,
    color: "bg-green-50",
    iconColor: "text-green-500",
  },
  {
    id: 3,
    icon: Flame,
    title: "Streak Master",
    description: "Login 30 consecutive days",
    unlocked: true,
    color: "bg-orange-100",
    iconColor: "text-orange-500",
  },
  {
    id: 4,
    icon: Cake,
    title: "Dessert Lover",
    description: "Create 20 dessert recipes",
    unlocked: false,
    color: "bg-pink-100",
    iconColor: "text-pink-500",
  },
  {
    id: 5,
    icon: Star,
    title: "Recipe Creator",
    description: "Publish 10 recipes",
    unlocked: true,
    color: "bg-yellow-100",
    iconColor: "text-yellow-500",
  },
  {
    id: 6,
    icon: Heart,
    title: "Community Favorite",
    description: "Receive 500 likes",
    unlocked: false,
    color: "bg-red-100",
    iconColor: "text-red-500",
  },
];